//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SetDkimKey.UtilsService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UtilsService.PrivateServiceSoap")]
    public interface PrivateServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAccountQueueCount", ReplyAction="*")]
        int GetAccountQueueCount(int AccountId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAccountQueueCount", ReplyAction="*")]
        System.Threading.Tasks.Task<int> GetAccountQueueCountAsync(int AccountId);
        
        // CODEGEN: Generating message contract since element name privateKey from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EncryptDomainKey", ReplyAction="*")]
        SetDkimKey.UtilsService.EncryptDomainKeyResponse EncryptDomainKey(SetDkimKey.UtilsService.EncryptDomainKeyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EncryptDomainKey", ReplyAction="*")]
        System.Threading.Tasks.Task<SetDkimKey.UtilsService.EncryptDomainKeyResponse> EncryptDomainKeyAsync(SetDkimKey.UtilsService.EncryptDomainKeyRequest request);
        
        // CODEGEN: Generating message contract since element name privateKey from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DecryptDomainKey", ReplyAction="*")]
        SetDkimKey.UtilsService.DecryptDomainKeyResponse DecryptDomainKey(SetDkimKey.UtilsService.DecryptDomainKeyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DecryptDomainKey", ReplyAction="*")]
        System.Threading.Tasks.Task<SetDkimKey.UtilsService.DecryptDomainKeyResponse> DecryptDomainKeyAsync(SetDkimKey.UtilsService.DecryptDomainKeyRequest request);
        
        // CODEGEN: Generating message contract since element name AddAccountResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddAccount", ReplyAction="*")]
        SetDkimKey.UtilsService.AddAccountResponse AddAccount(SetDkimKey.UtilsService.AddAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddAccount", ReplyAction="*")]
        System.Threading.Tasks.Task<SetDkimKey.UtilsService.AddAccountResponse> AddAccountAsync(SetDkimKey.UtilsService.AddAccountRequest request);
        
        // CODEGEN: Generating message contract since element name ExpungeQueueResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExpungeQueue", ReplyAction="*")]
        SetDkimKey.UtilsService.ExpungeQueueResponse ExpungeQueue(SetDkimKey.UtilsService.ExpungeQueueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExpungeQueue", ReplyAction="*")]
        System.Threading.Tasks.Task<SetDkimKey.UtilsService.ExpungeQueueResponse> ExpungeQueueAsync(SetDkimKey.UtilsService.ExpungeQueueRequest request);
        
        // CODEGEN: Generating message contract since element name ClearRestrictionsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ClearRestrictions", ReplyAction="*")]
        SetDkimKey.UtilsService.ClearRestrictionsResponse ClearRestrictions(SetDkimKey.UtilsService.ClearRestrictionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ClearRestrictions", ReplyAction="*")]
        System.Threading.Tasks.Task<SetDkimKey.UtilsService.ClearRestrictionsResponse> ClearRestrictionsAsync(SetDkimKey.UtilsService.ClearRestrictionsRequest request);
        
        // CODEGEN: Generating message contract since element name GetVersionResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetVersion", ReplyAction="*")]
        SetDkimKey.UtilsService.GetVersionResponse GetVersion(SetDkimKey.UtilsService.GetVersionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetVersion", ReplyAction="*")]
        System.Threading.Tasks.Task<SetDkimKey.UtilsService.GetVersionResponse> GetVersionAsync(SetDkimKey.UtilsService.GetVersionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EncryptDomainKeyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EncryptDomainKey", Namespace="http://tempuri.org/", Order=0)]
        public SetDkimKey.UtilsService.EncryptDomainKeyRequestBody Body;
        
        public EncryptDomainKeyRequest() {
        }
        
        public EncryptDomainKeyRequest(SetDkimKey.UtilsService.EncryptDomainKeyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EncryptDomainKeyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string privateKey;
        
        public EncryptDomainKeyRequestBody() {
        }
        
        public EncryptDomainKeyRequestBody(string privateKey) {
            this.privateKey = privateKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EncryptDomainKeyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EncryptDomainKeyResponse", Namespace="http://tempuri.org/", Order=0)]
        public SetDkimKey.UtilsService.EncryptDomainKeyResponseBody Body;
        
        public EncryptDomainKeyResponse() {
        }
        
        public EncryptDomainKeyResponse(SetDkimKey.UtilsService.EncryptDomainKeyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EncryptDomainKeyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EncryptDomainKeyResult;
        
        public EncryptDomainKeyResponseBody() {
        }
        
        public EncryptDomainKeyResponseBody(string EncryptDomainKeyResult) {
            this.EncryptDomainKeyResult = EncryptDomainKeyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DecryptDomainKeyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DecryptDomainKey", Namespace="http://tempuri.org/", Order=0)]
        public SetDkimKey.UtilsService.DecryptDomainKeyRequestBody Body;
        
        public DecryptDomainKeyRequest() {
        }
        
        public DecryptDomainKeyRequest(SetDkimKey.UtilsService.DecryptDomainKeyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DecryptDomainKeyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string privateKey;
        
        public DecryptDomainKeyRequestBody() {
        }
        
        public DecryptDomainKeyRequestBody(string privateKey) {
            this.privateKey = privateKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DecryptDomainKeyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DecryptDomainKeyResponse", Namespace="http://tempuri.org/", Order=0)]
        public SetDkimKey.UtilsService.DecryptDomainKeyResponseBody Body;
        
        public DecryptDomainKeyResponse() {
        }
        
        public DecryptDomainKeyResponse(SetDkimKey.UtilsService.DecryptDomainKeyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DecryptDomainKeyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DecryptDomainKeyResult;
        
        public DecryptDomainKeyResponseBody() {
        }
        
        public DecryptDomainKeyResponseBody(string DecryptDomainKeyResult) {
            this.DecryptDomainKeyResult = DecryptDomainKeyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddAccountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddAccount", Namespace="http://tempuri.org/", Order=0)]
        public SetDkimKey.UtilsService.AddAccountRequestBody Body;
        
        public AddAccountRequest() {
        }
        
        public AddAccountRequest(SetDkimKey.UtilsService.AddAccountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddAccountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int AccountId;
        
        public AddAccountRequestBody() {
        }
        
        public AddAccountRequestBody(int AccountId) {
            this.AccountId = AccountId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddAccountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddAccountResponse", Namespace="http://tempuri.org/", Order=0)]
        public SetDkimKey.UtilsService.AddAccountResponseBody Body;
        
        public AddAccountResponse() {
        }
        
        public AddAccountResponse(SetDkimKey.UtilsService.AddAccountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddAccountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddAccountResult;
        
        public AddAccountResponseBody() {
        }
        
        public AddAccountResponseBody(string AddAccountResult) {
            this.AddAccountResult = AddAccountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExpungeQueueRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExpungeQueue", Namespace="http://tempuri.org/", Order=0)]
        public SetDkimKey.UtilsService.ExpungeQueueRequestBody Body;
        
        public ExpungeQueueRequest() {
        }
        
        public ExpungeQueueRequest(SetDkimKey.UtilsService.ExpungeQueueRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ExpungeQueueRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int accountId;
        
        public ExpungeQueueRequestBody() {
        }
        
        public ExpungeQueueRequestBody(int accountId) {
            this.accountId = accountId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExpungeQueueResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExpungeQueueResponse", Namespace="http://tempuri.org/", Order=0)]
        public SetDkimKey.UtilsService.ExpungeQueueResponseBody Body;
        
        public ExpungeQueueResponse() {
        }
        
        public ExpungeQueueResponse(SetDkimKey.UtilsService.ExpungeQueueResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ExpungeQueueResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ExpungeQueueResult;
        
        public ExpungeQueueResponseBody() {
        }
        
        public ExpungeQueueResponseBody(string ExpungeQueueResult) {
            this.ExpungeQueueResult = ExpungeQueueResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ClearRestrictionsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ClearRestrictions", Namespace="http://tempuri.org/", Order=0)]
        public SetDkimKey.UtilsService.ClearRestrictionsRequestBody Body;
        
        public ClearRestrictionsRequest() {
        }
        
        public ClearRestrictionsRequest(SetDkimKey.UtilsService.ClearRestrictionsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ClearRestrictionsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int accountId;
        
        public ClearRestrictionsRequestBody() {
        }
        
        public ClearRestrictionsRequestBody(int accountId) {
            this.accountId = accountId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ClearRestrictionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ClearRestrictionsResponse", Namespace="http://tempuri.org/", Order=0)]
        public SetDkimKey.UtilsService.ClearRestrictionsResponseBody Body;
        
        public ClearRestrictionsResponse() {
        }
        
        public ClearRestrictionsResponse(SetDkimKey.UtilsService.ClearRestrictionsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ClearRestrictionsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ClearRestrictionsResult;
        
        public ClearRestrictionsResponseBody() {
        }
        
        public ClearRestrictionsResponseBody(string ClearRestrictionsResult) {
            this.ClearRestrictionsResult = ClearRestrictionsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetVersionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetVersion", Namespace="http://tempuri.org/", Order=0)]
        public SetDkimKey.UtilsService.GetVersionRequestBody Body;
        
        public GetVersionRequest() {
        }
        
        public GetVersionRequest(SetDkimKey.UtilsService.GetVersionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetVersionRequestBody {
        
        public GetVersionRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetVersionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetVersionResponse", Namespace="http://tempuri.org/", Order=0)]
        public SetDkimKey.UtilsService.GetVersionResponseBody Body;
        
        public GetVersionResponse() {
        }
        
        public GetVersionResponse(SetDkimKey.UtilsService.GetVersionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetVersionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetVersionResult;
        
        public GetVersionResponseBody() {
        }
        
        public GetVersionResponseBody(string GetVersionResult) {
            this.GetVersionResult = GetVersionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PrivateServiceSoapChannel : SetDkimKey.UtilsService.PrivateServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PrivateServiceSoapClient : System.ServiceModel.ClientBase<SetDkimKey.UtilsService.PrivateServiceSoap>, SetDkimKey.UtilsService.PrivateServiceSoap {
        
        public PrivateServiceSoapClient() {
        }
        
        public PrivateServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PrivateServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrivateServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrivateServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GetAccountQueueCount(int AccountId) {
            return base.Channel.GetAccountQueueCount(AccountId);
        }
        
        public System.Threading.Tasks.Task<int> GetAccountQueueCountAsync(int AccountId) {
            return base.Channel.GetAccountQueueCountAsync(AccountId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SetDkimKey.UtilsService.EncryptDomainKeyResponse SetDkimKey.UtilsService.PrivateServiceSoap.EncryptDomainKey(SetDkimKey.UtilsService.EncryptDomainKeyRequest request) {
            return base.Channel.EncryptDomainKey(request);
        }
        
        public string EncryptDomainKey(string privateKey) {
            SetDkimKey.UtilsService.EncryptDomainKeyRequest inValue = new SetDkimKey.UtilsService.EncryptDomainKeyRequest();
            inValue.Body = new SetDkimKey.UtilsService.EncryptDomainKeyRequestBody();
            inValue.Body.privateKey = privateKey;
            SetDkimKey.UtilsService.EncryptDomainKeyResponse retVal = ((SetDkimKey.UtilsService.PrivateServiceSoap)(this)).EncryptDomainKey(inValue);
            return retVal.Body.EncryptDomainKeyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SetDkimKey.UtilsService.EncryptDomainKeyResponse> SetDkimKey.UtilsService.PrivateServiceSoap.EncryptDomainKeyAsync(SetDkimKey.UtilsService.EncryptDomainKeyRequest request) {
            return base.Channel.EncryptDomainKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<SetDkimKey.UtilsService.EncryptDomainKeyResponse> EncryptDomainKeyAsync(string privateKey) {
            SetDkimKey.UtilsService.EncryptDomainKeyRequest inValue = new SetDkimKey.UtilsService.EncryptDomainKeyRequest();
            inValue.Body = new SetDkimKey.UtilsService.EncryptDomainKeyRequestBody();
            inValue.Body.privateKey = privateKey;
            return ((SetDkimKey.UtilsService.PrivateServiceSoap)(this)).EncryptDomainKeyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SetDkimKey.UtilsService.DecryptDomainKeyResponse SetDkimKey.UtilsService.PrivateServiceSoap.DecryptDomainKey(SetDkimKey.UtilsService.DecryptDomainKeyRequest request) {
            return base.Channel.DecryptDomainKey(request);
        }
        
        public string DecryptDomainKey(string privateKey) {
            SetDkimKey.UtilsService.DecryptDomainKeyRequest inValue = new SetDkimKey.UtilsService.DecryptDomainKeyRequest();
            inValue.Body = new SetDkimKey.UtilsService.DecryptDomainKeyRequestBody();
            inValue.Body.privateKey = privateKey;
            SetDkimKey.UtilsService.DecryptDomainKeyResponse retVal = ((SetDkimKey.UtilsService.PrivateServiceSoap)(this)).DecryptDomainKey(inValue);
            return retVal.Body.DecryptDomainKeyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SetDkimKey.UtilsService.DecryptDomainKeyResponse> SetDkimKey.UtilsService.PrivateServiceSoap.DecryptDomainKeyAsync(SetDkimKey.UtilsService.DecryptDomainKeyRequest request) {
            return base.Channel.DecryptDomainKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<SetDkimKey.UtilsService.DecryptDomainKeyResponse> DecryptDomainKeyAsync(string privateKey) {
            SetDkimKey.UtilsService.DecryptDomainKeyRequest inValue = new SetDkimKey.UtilsService.DecryptDomainKeyRequest();
            inValue.Body = new SetDkimKey.UtilsService.DecryptDomainKeyRequestBody();
            inValue.Body.privateKey = privateKey;
            return ((SetDkimKey.UtilsService.PrivateServiceSoap)(this)).DecryptDomainKeyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SetDkimKey.UtilsService.AddAccountResponse SetDkimKey.UtilsService.PrivateServiceSoap.AddAccount(SetDkimKey.UtilsService.AddAccountRequest request) {
            return base.Channel.AddAccount(request);
        }
        
        public string AddAccount(int AccountId) {
            SetDkimKey.UtilsService.AddAccountRequest inValue = new SetDkimKey.UtilsService.AddAccountRequest();
            inValue.Body = new SetDkimKey.UtilsService.AddAccountRequestBody();
            inValue.Body.AccountId = AccountId;
            SetDkimKey.UtilsService.AddAccountResponse retVal = ((SetDkimKey.UtilsService.PrivateServiceSoap)(this)).AddAccount(inValue);
            return retVal.Body.AddAccountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SetDkimKey.UtilsService.AddAccountResponse> SetDkimKey.UtilsService.PrivateServiceSoap.AddAccountAsync(SetDkimKey.UtilsService.AddAccountRequest request) {
            return base.Channel.AddAccountAsync(request);
        }
        
        public System.Threading.Tasks.Task<SetDkimKey.UtilsService.AddAccountResponse> AddAccountAsync(int AccountId) {
            SetDkimKey.UtilsService.AddAccountRequest inValue = new SetDkimKey.UtilsService.AddAccountRequest();
            inValue.Body = new SetDkimKey.UtilsService.AddAccountRequestBody();
            inValue.Body.AccountId = AccountId;
            return ((SetDkimKey.UtilsService.PrivateServiceSoap)(this)).AddAccountAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SetDkimKey.UtilsService.ExpungeQueueResponse SetDkimKey.UtilsService.PrivateServiceSoap.ExpungeQueue(SetDkimKey.UtilsService.ExpungeQueueRequest request) {
            return base.Channel.ExpungeQueue(request);
        }
        
        public string ExpungeQueue(int accountId) {
            SetDkimKey.UtilsService.ExpungeQueueRequest inValue = new SetDkimKey.UtilsService.ExpungeQueueRequest();
            inValue.Body = new SetDkimKey.UtilsService.ExpungeQueueRequestBody();
            inValue.Body.accountId = accountId;
            SetDkimKey.UtilsService.ExpungeQueueResponse retVal = ((SetDkimKey.UtilsService.PrivateServiceSoap)(this)).ExpungeQueue(inValue);
            return retVal.Body.ExpungeQueueResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SetDkimKey.UtilsService.ExpungeQueueResponse> SetDkimKey.UtilsService.PrivateServiceSoap.ExpungeQueueAsync(SetDkimKey.UtilsService.ExpungeQueueRequest request) {
            return base.Channel.ExpungeQueueAsync(request);
        }
        
        public System.Threading.Tasks.Task<SetDkimKey.UtilsService.ExpungeQueueResponse> ExpungeQueueAsync(int accountId) {
            SetDkimKey.UtilsService.ExpungeQueueRequest inValue = new SetDkimKey.UtilsService.ExpungeQueueRequest();
            inValue.Body = new SetDkimKey.UtilsService.ExpungeQueueRequestBody();
            inValue.Body.accountId = accountId;
            return ((SetDkimKey.UtilsService.PrivateServiceSoap)(this)).ExpungeQueueAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SetDkimKey.UtilsService.ClearRestrictionsResponse SetDkimKey.UtilsService.PrivateServiceSoap.ClearRestrictions(SetDkimKey.UtilsService.ClearRestrictionsRequest request) {
            return base.Channel.ClearRestrictions(request);
        }
        
        public string ClearRestrictions(int accountId) {
            SetDkimKey.UtilsService.ClearRestrictionsRequest inValue = new SetDkimKey.UtilsService.ClearRestrictionsRequest();
            inValue.Body = new SetDkimKey.UtilsService.ClearRestrictionsRequestBody();
            inValue.Body.accountId = accountId;
            SetDkimKey.UtilsService.ClearRestrictionsResponse retVal = ((SetDkimKey.UtilsService.PrivateServiceSoap)(this)).ClearRestrictions(inValue);
            return retVal.Body.ClearRestrictionsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SetDkimKey.UtilsService.ClearRestrictionsResponse> SetDkimKey.UtilsService.PrivateServiceSoap.ClearRestrictionsAsync(SetDkimKey.UtilsService.ClearRestrictionsRequest request) {
            return base.Channel.ClearRestrictionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<SetDkimKey.UtilsService.ClearRestrictionsResponse> ClearRestrictionsAsync(int accountId) {
            SetDkimKey.UtilsService.ClearRestrictionsRequest inValue = new SetDkimKey.UtilsService.ClearRestrictionsRequest();
            inValue.Body = new SetDkimKey.UtilsService.ClearRestrictionsRequestBody();
            inValue.Body.accountId = accountId;
            return ((SetDkimKey.UtilsService.PrivateServiceSoap)(this)).ClearRestrictionsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SetDkimKey.UtilsService.GetVersionResponse SetDkimKey.UtilsService.PrivateServiceSoap.GetVersion(SetDkimKey.UtilsService.GetVersionRequest request) {
            return base.Channel.GetVersion(request);
        }
        
        public string GetVersion() {
            SetDkimKey.UtilsService.GetVersionRequest inValue = new SetDkimKey.UtilsService.GetVersionRequest();
            inValue.Body = new SetDkimKey.UtilsService.GetVersionRequestBody();
            SetDkimKey.UtilsService.GetVersionResponse retVal = ((SetDkimKey.UtilsService.PrivateServiceSoap)(this)).GetVersion(inValue);
            return retVal.Body.GetVersionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SetDkimKey.UtilsService.GetVersionResponse> SetDkimKey.UtilsService.PrivateServiceSoap.GetVersionAsync(SetDkimKey.UtilsService.GetVersionRequest request) {
            return base.Channel.GetVersionAsync(request);
        }
        
        public System.Threading.Tasks.Task<SetDkimKey.UtilsService.GetVersionResponse> GetVersionAsync() {
            SetDkimKey.UtilsService.GetVersionRequest inValue = new SetDkimKey.UtilsService.GetVersionRequest();
            inValue.Body = new SetDkimKey.UtilsService.GetVersionRequestBody();
            return ((SetDkimKey.UtilsService.PrivateServiceSoap)(this)).GetVersionAsync(inValue);
        }
    }
}
