//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SetDkimKey.AccountSettings {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="http://tempuri.org/", ItemName="int")]
    [System.SerializableAttribute()]
    public class ArrayOfInt : System.Collections.Generic.List<int> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SettingKeyValuePair", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SetDkimKey.AccountSettings.ArrayOfInt))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SetDkimKey.AccountSettings.SettingKeyValuePair[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SetDkimKey.AccountSettings.ArrayOfString))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SetDkimKey.AccountSettings.AccountDeleteOptions))]
    public partial class SettingKeyValuePair : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object ValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public object Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountDeleteOptions", Namespace="http://tempuri.org/")]
    public enum AccountDeleteOptions : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Delete = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Undelete = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PermanentlyDelete = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AccountSettings.AccountServiceSoap")]
    public interface AccountServiceSoap {
        
        // CODEGEN: Generating message contract since element name userName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Find", ReplyAction="*")]
        SetDkimKey.AccountSettings.FindResponse Find(SetDkimKey.AccountSettings.FindRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Find", ReplyAction="*")]
        System.Threading.Tasks.Task<SetDkimKey.AccountSettings.FindResponse> FindAsync(SetDkimKey.AccountSettings.FindRequest request);
        
        // CODEGEN: Generating message contract since element name type from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSettings", ReplyAction="*")]
        SetDkimKey.AccountSettings.GetSettingsResponse GetSettings(SetDkimKey.AccountSettings.GetSettingsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSettings", ReplyAction="*")]
        System.Threading.Tasks.Task<SetDkimKey.AccountSettings.GetSettingsResponse> GetSettingsAsync(SetDkimKey.AccountSettings.GetSettingsRequest request);
        
        // CODEGEN: Generating message contract since element name type from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetSettings", ReplyAction="*")]
        SetDkimKey.AccountSettings.SetSettingsResponse SetSettings(SetDkimKey.AccountSettings.SetSettingsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetSettings", ReplyAction="*")]
        System.Threading.Tasks.Task<SetDkimKey.AccountSettings.SetSettingsResponse> SetSettingsAsync(SetDkimKey.AccountSettings.SetSettingsRequest request);
        
        // CODEGEN: Generating message contract since element name type from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EnumSections", ReplyAction="*")]
        SetDkimKey.AccountSettings.EnumSectionsResponse EnumSections(SetDkimKey.AccountSettings.EnumSectionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EnumSections", ReplyAction="*")]
        System.Threading.Tasks.Task<SetDkimKey.AccountSettings.EnumSectionsResponse> EnumSectionsAsync(SetDkimKey.AccountSettings.EnumSectionsRequest request);
        
        // CODEGEN: Generating message contract since element name friendlyName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Create", ReplyAction="*")]
        SetDkimKey.AccountSettings.CreateResponse Create(SetDkimKey.AccountSettings.CreateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Create", ReplyAction="*")]
        System.Threading.Tasks.Task<SetDkimKey.AccountSettings.CreateResponse> CreateAsync(SetDkimKey.AccountSettings.CreateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        void Delete(int accountId, SetDkimKey.AccountSettings.AccountDeleteOptions options);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        System.Threading.Tasks.Task DeleteAsync(int accountId, SetDkimKey.AccountSettings.AccountDeleteOptions options);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Find", Namespace="http://tempuri.org/", Order=0)]
        public SetDkimKey.AccountSettings.FindRequestBody Body;
        
        public FindRequest() {
        }
        
        public FindRequest(SetDkimKey.AccountSettings.FindRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public bool includeDeleted;
        
        public FindRequestBody() {
        }
        
        public FindRequestBody(string userName, bool includeDeleted) {
            this.userName = userName;
            this.includeDeleted = includeDeleted;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindResponse", Namespace="http://tempuri.org/", Order=0)]
        public SetDkimKey.AccountSettings.FindResponseBody Body;
        
        public FindResponse() {
        }
        
        public FindResponse(SetDkimKey.AccountSettings.FindResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SetDkimKey.AccountSettings.ArrayOfInt FindResult;
        
        public FindResponseBody() {
        }
        
        public FindResponseBody(SetDkimKey.AccountSettings.ArrayOfInt FindResult) {
            this.FindResult = FindResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSettingsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSettings", Namespace="http://tempuri.org/", Order=0)]
        public SetDkimKey.AccountSettings.GetSettingsRequestBody Body;
        
        public GetSettingsRequest() {
        }
        
        public GetSettingsRequest(SetDkimKey.AccountSettings.GetSettingsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSettingsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int accountId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string type;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string section;
        
        public GetSettingsRequestBody() {
        }
        
        public GetSettingsRequestBody(int accountId, string type, string section) {
            this.accountId = accountId;
            this.type = type;
            this.section = section;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSettingsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSettingsResponse", Namespace="http://tempuri.org/", Order=0)]
        public SetDkimKey.AccountSettings.GetSettingsResponseBody Body;
        
        public GetSettingsResponse() {
        }
        
        public GetSettingsResponse(SetDkimKey.AccountSettings.GetSettingsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSettingsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SetDkimKey.AccountSettings.SettingKeyValuePair[] GetSettingsResult;
        
        public GetSettingsResponseBody() {
        }
        
        public GetSettingsResponseBody(SetDkimKey.AccountSettings.SettingKeyValuePair[] GetSettingsResult) {
            this.GetSettingsResult = GetSettingsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetSettingsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetSettings", Namespace="http://tempuri.org/", Order=0)]
        public SetDkimKey.AccountSettings.SetSettingsRequestBody Body;
        
        public SetSettingsRequest() {
        }
        
        public SetSettingsRequest(SetDkimKey.AccountSettings.SetSettingsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetSettingsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int accountId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string type;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string section;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public SetDkimKey.AccountSettings.SettingKeyValuePair[] items;
        
        public SetSettingsRequestBody() {
        }
        
        public SetSettingsRequestBody(int accountId, string type, string section, SetDkimKey.AccountSettings.SettingKeyValuePair[] items) {
            this.accountId = accountId;
            this.type = type;
            this.section = section;
            this.items = items;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetSettingsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetSettingsResponse", Namespace="http://tempuri.org/", Order=0)]
        public SetDkimKey.AccountSettings.SetSettingsResponseBody Body;
        
        public SetSettingsResponse() {
        }
        
        public SetSettingsResponse(SetDkimKey.AccountSettings.SetSettingsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SetSettingsResponseBody {
        
        public SetSettingsResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnumSectionsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnumSections", Namespace="http://tempuri.org/", Order=0)]
        public SetDkimKey.AccountSettings.EnumSectionsRequestBody Body;
        
        public EnumSectionsRequest() {
        }
        
        public EnumSectionsRequest(SetDkimKey.AccountSettings.EnumSectionsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EnumSectionsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int accountId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string type;
        
        public EnumSectionsRequestBody() {
        }
        
        public EnumSectionsRequestBody(int accountId, string type) {
            this.accountId = accountId;
            this.type = type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnumSectionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnumSectionsResponse", Namespace="http://tempuri.org/", Order=0)]
        public SetDkimKey.AccountSettings.EnumSectionsResponseBody Body;
        
        public EnumSectionsResponse() {
        }
        
        public EnumSectionsResponse(SetDkimKey.AccountSettings.EnumSectionsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EnumSectionsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SetDkimKey.AccountSettings.ArrayOfString EnumSectionsResult;
        
        public EnumSectionsResponseBody() {
        }
        
        public EnumSectionsResponseBody(SetDkimKey.AccountSettings.ArrayOfString EnumSectionsResult) {
            this.EnumSectionsResult = EnumSectionsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Create", Namespace="http://tempuri.org/", Order=0)]
        public SetDkimKey.AccountSettings.CreateRequestBody Body;
        
        public CreateRequest() {
        }
        
        public CreateRequest(SetDkimKey.AccountSettings.CreateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string friendlyName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string basePath;
        
        public CreateRequestBody() {
        }
        
        public CreateRequestBody(string friendlyName, string userName, string password, string basePath) {
            this.friendlyName = friendlyName;
            this.userName = userName;
            this.password = password;
            this.basePath = basePath;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateResponse", Namespace="http://tempuri.org/", Order=0)]
        public SetDkimKey.AccountSettings.CreateResponseBody Body;
        
        public CreateResponse() {
        }
        
        public CreateResponse(SetDkimKey.AccountSettings.CreateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int CreateResult;
        
        public CreateResponseBody() {
        }
        
        public CreateResponseBody(int CreateResult) {
            this.CreateResult = CreateResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AccountServiceSoapChannel : SetDkimKey.AccountSettings.AccountServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccountServiceSoapClient : System.ServiceModel.ClientBase<SetDkimKey.AccountSettings.AccountServiceSoap>, SetDkimKey.AccountSettings.AccountServiceSoap {
        
        public AccountServiceSoapClient() {
        }
        
        public AccountServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccountServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SetDkimKey.AccountSettings.FindResponse SetDkimKey.AccountSettings.AccountServiceSoap.Find(SetDkimKey.AccountSettings.FindRequest request) {
            return base.Channel.Find(request);
        }
        
        public SetDkimKey.AccountSettings.ArrayOfInt Find(string userName, bool includeDeleted) {
            SetDkimKey.AccountSettings.FindRequest inValue = new SetDkimKey.AccountSettings.FindRequest();
            inValue.Body = new SetDkimKey.AccountSettings.FindRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.includeDeleted = includeDeleted;
            SetDkimKey.AccountSettings.FindResponse retVal = ((SetDkimKey.AccountSettings.AccountServiceSoap)(this)).Find(inValue);
            return retVal.Body.FindResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SetDkimKey.AccountSettings.FindResponse> SetDkimKey.AccountSettings.AccountServiceSoap.FindAsync(SetDkimKey.AccountSettings.FindRequest request) {
            return base.Channel.FindAsync(request);
        }
        
        public System.Threading.Tasks.Task<SetDkimKey.AccountSettings.FindResponse> FindAsync(string userName, bool includeDeleted) {
            SetDkimKey.AccountSettings.FindRequest inValue = new SetDkimKey.AccountSettings.FindRequest();
            inValue.Body = new SetDkimKey.AccountSettings.FindRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.includeDeleted = includeDeleted;
            return ((SetDkimKey.AccountSettings.AccountServiceSoap)(this)).FindAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SetDkimKey.AccountSettings.GetSettingsResponse SetDkimKey.AccountSettings.AccountServiceSoap.GetSettings(SetDkimKey.AccountSettings.GetSettingsRequest request) {
            return base.Channel.GetSettings(request);
        }
        
        public SetDkimKey.AccountSettings.SettingKeyValuePair[] GetSettings(int accountId, string type, string section) {
            SetDkimKey.AccountSettings.GetSettingsRequest inValue = new SetDkimKey.AccountSettings.GetSettingsRequest();
            inValue.Body = new SetDkimKey.AccountSettings.GetSettingsRequestBody();
            inValue.Body.accountId = accountId;
            inValue.Body.type = type;
            inValue.Body.section = section;
            SetDkimKey.AccountSettings.GetSettingsResponse retVal = ((SetDkimKey.AccountSettings.AccountServiceSoap)(this)).GetSettings(inValue);
            return retVal.Body.GetSettingsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SetDkimKey.AccountSettings.GetSettingsResponse> SetDkimKey.AccountSettings.AccountServiceSoap.GetSettingsAsync(SetDkimKey.AccountSettings.GetSettingsRequest request) {
            return base.Channel.GetSettingsAsync(request);
        }
        
        public System.Threading.Tasks.Task<SetDkimKey.AccountSettings.GetSettingsResponse> GetSettingsAsync(int accountId, string type, string section) {
            SetDkimKey.AccountSettings.GetSettingsRequest inValue = new SetDkimKey.AccountSettings.GetSettingsRequest();
            inValue.Body = new SetDkimKey.AccountSettings.GetSettingsRequestBody();
            inValue.Body.accountId = accountId;
            inValue.Body.type = type;
            inValue.Body.section = section;
            return ((SetDkimKey.AccountSettings.AccountServiceSoap)(this)).GetSettingsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SetDkimKey.AccountSettings.SetSettingsResponse SetDkimKey.AccountSettings.AccountServiceSoap.SetSettings(SetDkimKey.AccountSettings.SetSettingsRequest request) {
            return base.Channel.SetSettings(request);
        }
        
        public void SetSettings(int accountId, string type, string section, SetDkimKey.AccountSettings.SettingKeyValuePair[] items) {
            SetDkimKey.AccountSettings.SetSettingsRequest inValue = new SetDkimKey.AccountSettings.SetSettingsRequest();
            inValue.Body = new SetDkimKey.AccountSettings.SetSettingsRequestBody();
            inValue.Body.accountId = accountId;
            inValue.Body.type = type;
            inValue.Body.section = section;
            inValue.Body.items = items;
            SetDkimKey.AccountSettings.SetSettingsResponse retVal = ((SetDkimKey.AccountSettings.AccountServiceSoap)(this)).SetSettings(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SetDkimKey.AccountSettings.SetSettingsResponse> SetDkimKey.AccountSettings.AccountServiceSoap.SetSettingsAsync(SetDkimKey.AccountSettings.SetSettingsRequest request) {
            return base.Channel.SetSettingsAsync(request);
        }
        
        public System.Threading.Tasks.Task<SetDkimKey.AccountSettings.SetSettingsResponse> SetSettingsAsync(int accountId, string type, string section, SetDkimKey.AccountSettings.SettingKeyValuePair[] items) {
            SetDkimKey.AccountSettings.SetSettingsRequest inValue = new SetDkimKey.AccountSettings.SetSettingsRequest();
            inValue.Body = new SetDkimKey.AccountSettings.SetSettingsRequestBody();
            inValue.Body.accountId = accountId;
            inValue.Body.type = type;
            inValue.Body.section = section;
            inValue.Body.items = items;
            return ((SetDkimKey.AccountSettings.AccountServiceSoap)(this)).SetSettingsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SetDkimKey.AccountSettings.EnumSectionsResponse SetDkimKey.AccountSettings.AccountServiceSoap.EnumSections(SetDkimKey.AccountSettings.EnumSectionsRequest request) {
            return base.Channel.EnumSections(request);
        }
        
        public SetDkimKey.AccountSettings.ArrayOfString EnumSections(int accountId, string type) {
            SetDkimKey.AccountSettings.EnumSectionsRequest inValue = new SetDkimKey.AccountSettings.EnumSectionsRequest();
            inValue.Body = new SetDkimKey.AccountSettings.EnumSectionsRequestBody();
            inValue.Body.accountId = accountId;
            inValue.Body.type = type;
            SetDkimKey.AccountSettings.EnumSectionsResponse retVal = ((SetDkimKey.AccountSettings.AccountServiceSoap)(this)).EnumSections(inValue);
            return retVal.Body.EnumSectionsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SetDkimKey.AccountSettings.EnumSectionsResponse> SetDkimKey.AccountSettings.AccountServiceSoap.EnumSectionsAsync(SetDkimKey.AccountSettings.EnumSectionsRequest request) {
            return base.Channel.EnumSectionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<SetDkimKey.AccountSettings.EnumSectionsResponse> EnumSectionsAsync(int accountId, string type) {
            SetDkimKey.AccountSettings.EnumSectionsRequest inValue = new SetDkimKey.AccountSettings.EnumSectionsRequest();
            inValue.Body = new SetDkimKey.AccountSettings.EnumSectionsRequestBody();
            inValue.Body.accountId = accountId;
            inValue.Body.type = type;
            return ((SetDkimKey.AccountSettings.AccountServiceSoap)(this)).EnumSectionsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SetDkimKey.AccountSettings.CreateResponse SetDkimKey.AccountSettings.AccountServiceSoap.Create(SetDkimKey.AccountSettings.CreateRequest request) {
            return base.Channel.Create(request);
        }
        
        public int Create(string friendlyName, string userName, string password, string basePath) {
            SetDkimKey.AccountSettings.CreateRequest inValue = new SetDkimKey.AccountSettings.CreateRequest();
            inValue.Body = new SetDkimKey.AccountSettings.CreateRequestBody();
            inValue.Body.friendlyName = friendlyName;
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.basePath = basePath;
            SetDkimKey.AccountSettings.CreateResponse retVal = ((SetDkimKey.AccountSettings.AccountServiceSoap)(this)).Create(inValue);
            return retVal.Body.CreateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SetDkimKey.AccountSettings.CreateResponse> SetDkimKey.AccountSettings.AccountServiceSoap.CreateAsync(SetDkimKey.AccountSettings.CreateRequest request) {
            return base.Channel.CreateAsync(request);
        }
        
        public System.Threading.Tasks.Task<SetDkimKey.AccountSettings.CreateResponse> CreateAsync(string friendlyName, string userName, string password, string basePath) {
            SetDkimKey.AccountSettings.CreateRequest inValue = new SetDkimKey.AccountSettings.CreateRequest();
            inValue.Body = new SetDkimKey.AccountSettings.CreateRequestBody();
            inValue.Body.friendlyName = friendlyName;
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.basePath = basePath;
            return ((SetDkimKey.AccountSettings.AccountServiceSoap)(this)).CreateAsync(inValue);
        }
        
        public void Delete(int accountId, SetDkimKey.AccountSettings.AccountDeleteOptions options) {
            base.Channel.Delete(accountId, options);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(int accountId, SetDkimKey.AccountSettings.AccountDeleteOptions options) {
            return base.Channel.DeleteAsync(accountId, options);
        }
    }
}
